### ISSUE TITLE
All chat messages appear twice

### ISSUE THREAD

**Issue by Valiec** [TallWorlds/CubicChunks#14] opened 2015-04-22 02:51 UTC
Just like the title says, all messages printed to the chat appear twice. There are no spaces or newlines between the duplicate outputs.

Example: I was setting the time to 1000 (I didn't want it to be night in my testing world). I did "/time set 1000" and this was outputted in the chat:

"Set the time to 1000Set the time to 1000"

**Comment by Drayux** [comment] 2015-05-04 01:43
Same here, man! I got the error just with the magic mojo launcher alone... it was before I installed cubic chunks. I am not an advanced programmer, nor am I developing this, but it is likely caused by something to do with forgetting a line break in the code and/or reusing an output string...something. XD

**Comment by mikesmiffy128** [comment] 2015-05-04 10:51
eh... Forgetting a line break in Java has no effect on anything. If it did there would be a compile error. Plus you can't really forget a line break. The return key is the biggest key on a keyboard. ~~This is probably caused by a missing client / server context check somewhere which means the chat rendering code is called from both sides.~~ I don't even know what causes this any more. Anyway, for some reason M3L inherits the same odd design of Forge by which identical code is run on a client and server (Is it a vanilla thing too? It just seems so daft).

Oh, while I'm here, I may as well confirm that I also experienced this issue a while ago and I did assume it was probably M3L rather than Tall Worlds causing it. To be honest it would be logical to close this issue and reopen it over on [Bitbucket](https://bitbucket.org/cuchaz/m3l/issues/new), but it doesn't matter much really.

**Comment by ajthemacboy** [comment] 2015-05-04 13:22
Can confirm. Also happens when hovering over achievements in chat; the description is doubled.

**Comment by mikesmiffy128** [comment] 2015-05-04 13:53
Hovering over achievements? Well that's... just weird.

**Comment by AttackOfTheDirt** [comment] 2015-05-04 13:59
That is m3l not the tall worlds mod. Happened to me with m3l beta 0.1  without the tall worlds mod. Put this issue for m3l not tall worlds.

**Comment by AttackOfTheDirt** [comment] 2015-05-04 14:00
M3l causes this.

**Comment by AttackOfTheDirt** [comment] 2015-05-04 14:03
I reported this issue for m3l on the m3l fprum thread already. Skin customisation and twitch broadcasting text gets duplicated so does the text that appears when a server log in fails. I have also already uploaded screenshots on the m3l forum thread. I have already reported this idsue on the minecraft forums.

**Comment by AttackOfTheDirt** [comment] 2015-05-04 14:07
Mikesmithy 128 is 100% correct about it being m3l issue, just I have already reported this issue and EVERYTHING about it on the m3l minecraft forum thread. First m3l issue ever reported was me reporting text duplication on the minecraft forum m3l thread.

**Comment by mikesmiffy128** [comment] 2015-05-04 15:07
Oh God! Calm down mate! You don't need to post 4 replies in a row saying the same thing. By the way, I linked the BitBucket bug tracker for a reason. Reporting on the forum probably works too, but there are existing issues on the BitBucket so you're wrong about it being the first issue ever reported. lol

Seriously though, mind the spam; keep in mind everyone gets an email whenever someone replies.

**Comment by Razaekel** [comment] 2015-05-05 23:20
M3L issue.

**Closed as completed by Razaekel** 2015-05-05 23:20 UTC
Labels: wontfix
