### ISSUE TITLE
Fill command doesn't work for areas beyond normal Minecraft height limits

### ISSUE THREAD

**Issue by Imnuts7** [TallWorlds/CubicChunks#18] opened 2015-04-22 07:19 UTC
So when I try to use the fill command for y levels >256 and <0, it comes up as the same reply that you would get in normal Minecraft, that the number entered is too big or small.

**Comment by kvverti** [comment] 2015-04-22 19:02
Make that _all_ commands except for /tp.

**Comment by Valiec** [comment] 2015-04-23 02:50
I reported something very like this (a.k.a the same thing but I'm leaving it to the devs to actually say which one is a duplicate of of the other, or if they are duplicates at all) in issue #15. It seems to be a hard-coded cap of some sort.

**Comment by Razaekel** [comment] 2015-04-23 23:33
Duplicate of #15

**Closed as completed by Razaekel** 2015-04-23 23:33 UTC
Labels: duplicate
