### ISSUE TITLE
Saving issues in chunks that unload

### ISSUE THREAD

**Issue by Drayux** [TallWorlds/CubicChunks#28] opened 2015-04-26 18:57 UTC
Hello! This is the first of a couple bugs I will report on this. Basically what goes on is that for any changes I make to a chunk, if that chunk is unloaded shortly afterward, more often than not, the changes I made will not be saved. If I should add any more information, let me know and I will add it, but that is the general description of what is going on. There is no crashes associated with it, but some of the time I will also only see the loss of data after reloading or exiting.

**Comment by kvverti** [comment] 2015-04-26 20:39
This is caused by the server not saving chunks in time when the game closes, causing queued chunks to be thrown away (see #11 )

**Comment by cuchaz** [comment] 2015-04-29 02:27
This might also have been caused by some broken IO thread synchronization, which I just fixed in 93af916a47b53f565e8020a9d25c5a3109a5456e

**Closed as completed** 2015-04-29 02:33 UTC
